version: "3.1"

services:
    engine-database:
        image: mysql:8.0
        platform: linux/amd64
        ports: 
            - "3307:3306"
        environment:
            MYSQL_DATABASE: engineDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - datafiles:/var/lib/mysql
        restart: always
        healthcheck:
            test: "mysql engineDB -uadmin -padmin -e 'SELECT 1;'"
            interval: 20s
            timeout: 10s
            retries: 2

    engine-service:
      depends_on:
        engine-database:
          condition: service_healthy
      build: ./projEngineService
      restart: always
      ports:
        - 6869:8001
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://engine-database:3306/engineDB?useSSL=true&createDatabaseIfNotExist=true",
          "spring.datasource.username" : "admin",
          "spring.datasource.password" : "admin",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jackson.serialization.fail-on-empty-beans" : false,
          "server.port": 8001 }'
      healthcheck:
        test: "curl http://localhost:8001"
        interval: 20s
        timeout: 10s
        retries: 2

    engine-frontend:
        build:
          context: ./projEngineWeb
          dockerfile: ./Dockerfile
        ports: 
          - '4200:80'
    
volumes:
   datafiles: