version: "3"

services: 
  specific_service:
    build: ./projSpecificService
    ports:
      - 8080:8080

  specific_db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : "password"
      MYSQL_DATABASE : "tqs_specific"
      MYSQL_USER : "tqs-specific"
      MYSQL_PASSWORD : "password"