version: "3"

services: 
  engine_service:
    build: ./projEngineService
    ports:
      - 8080:8080

  engine_db:
    image: mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD : "password"
      MYSQL_DATABASE : "tqs_generic"
      MYSQL_USER : "tqs-generic"
      MYSQL_PASSWORD : "password"