
version: "3.1"

services:
    specificDataBase:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: specificDB
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin 
        volumes:
            - datafiles:/var/lib/mysql
        networks:
            - default
        restart: always
        healthcheck:
            test: "mysql specificDB -uadmin -padmin -e 'SELECT 1;'"
            interval: 20s
            timeout: 10s
            retries: 2

#    generalDataBase:
#        image: mysql:8.0
#        platform: linux/amd64
#        ports: 
#            - "3307:3306"
#        environment:
#            MYSQL_DATABASE: generalDB
#            MYSQL_USER: admin
#            MYSQL_ROOT_PASSWORD: admin
#            MYSQL_PASSWORD: admin 
#        volumes:
#            - datafiles:/var/lib/mysql
#        networks:
#            - default
#        restart: always
#        healthcheck:
#            test: "mysql generalDB -uadmin -padmin -e 'SELECT 1;'"
#            interval: 20s
#            timeout: 10s
#            retries: 2

#    projspecificservice:
#      depends_on:
#        specificDataBase:
#          condition: service_healthy
#      build: ./projSpecificService
#      restart: on-failure
#      ports:
#        - 6868:8000
#      environment:
#        SPRING_APPLICATION_JSON: '{
#          "spring.datasource.url"  : "jdbc:mysql://specificDataBase:3306/specificDB?useSSL=true",
#          "spring.datasource.username" : "admin",
#          "spring.datasource.password" : "admin",
#          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
#          "spring.jpa.hibernate.ddl-auto" : "update",
#          "server.port": 8000 }'
#      healthcheck:
#        test: "curl http://localhost:8000"
#        interval: 20s
#        timeout: 10s
#        retries: 2

#    projgeneralservice:
#      depends_on:
#        generalDataBase:
#          condition: service_healthy
#      build: ./projEngineService
#      restart: on-failure
#      ports:
#        - 6869:8001
#      environment:
#        SPRING_APPLICATION_JSON: '{
#          "spring.datasource.url"  : "jdbc:mysql://generalDataBase:3306/generalDB?useSSL=true",
#          "spring.datasource.username" : "admin",
#          "spring.datasource.password" : "admin",
#          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
#          "spring.jpa.hibernate.ddl-auto" : "update",
#          "server.port": 8001 }'
#      healthcheck:
#        test: "curl http://localhost:8001"
#        interval: 20s
#        timeout: 10s
#        retries: 2
    
volumes:
  datafiles: