name: Spring-Boot CI Tests Specific

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latests
    name: Running 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses:  actions/setup-java@v2      
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build Generic Service
        run: docker-compose build --build-arg PROFILE=CI --build-arg GENERIC_URL=localhost generic
      - name: Start Generic Service on Docker
        run: docker-compose up -d 

    working-directory: ./projSpecificService
    
