name: Spring-Boot CI Tests Specific

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-18.04
    name: Running 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses:  actions/setup-java@v2      
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests with Maven
        run: |
          cd projSpecificService
          mvn test
    
